const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeArray=k=>{try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return []}};
const st={loading:true,user:null,profile:null,counts:null,message:'',error:''};
function layout(body){return `<main class="admin-shell"><div class="admin-top"><div><div class="eyebrow">Founder tools • secure cloud bridge</div><h1>English Haters Cloud Publisher</h1><div class="muted">Authenticate as an admin, then publish reviewed local content to the student cloud.</div></div><div class="admin-actions"><a class="small-btn" href="admin.html">← Content Admin</a><a class="small-btn" href="index.html">Student app</a></div></div>${body}</main>`}
function render(){
  if(!EHBackend?.enabled){$('#cloudAdminApp').innerHTML=layout(`<div class="notice"><b>Cloud mode is not configured.</b> Open <code>SETUP-SUPABASE.md</code>, create the free Supabase project, run <code>supabase-setup.sql</code>, then paste your project URL/key into <code>backend-config.js</code>.</div><div class="panel"><h2>Why this page exists</h2><p class="muted">The normal Content Admin stays fast and local for writing/importing. This page is the protected publishing gate. Student accounts can read published content but cannot change it.</p></div>`);return}
  if(st.loading){$('#cloudAdminApp').innerHTML=layout(`<div class="panel"><h2>Checking admin session…</h2><p class="muted">Connecting to the cloud backend.</p></div>`);return}
  if(!st.user){$('#cloudAdminApp').innerHTML=layout(`<div class="panel"><div class="panel-head"><div><h2>Admin sign in</h2><div class="muted">Use the founder account whose profile role is set to admin.</div></div></div>${st.error?`<div class="validation bad">${esc(st.error)}</div>`:''}${st.message?`<div class="validation ok">${esc(st.message)}</div>`:''}<form id="adminLogin"><div class="form-grid"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="6" required></div></div><div class="form-actions"><button class="small-btn primary" type="submit">Sign in securely</button></div></form></div>`);bind();return}
  if(st.profile?.role!=='admin'){$('#cloudAdminApp').innerHTML=layout(`<div class="validation bad"><b>Access denied.</b> This signed-in account is not an English Haters admin.</div><div class="panel"><p class="muted">For the founder account, use the one-time role command shown at the bottom of <code>supabase-setup.sql</code>.</p><button class="small-btn" id="cloudSignOut">Sign out</button></div>`);bind();return}
  const qs=safeArray('eh_custom_questions'),ls=safeArray('eh_custom_lessons');const approved=qs.filter(q=>(q.review_status||'draft')==='approved'&&q.published!==false).length;const pending=qs.filter(q=>['draft','review'].includes(q.review_status||'draft')).length;
  $('#cloudAdminApp').innerHTML=layout(`${st.error?`<div class="validation bad">${esc(st.error)}</div>`:''}${st.message?`<div class="validation ok">${esc(st.message)}</div>`:''}<div class="admin-grid"><div class="card admin-stat"><b>${qs.length}</b><span>local questions</span></div><div class="card admin-stat"><b>${approved}</b><span>approved to publish</span></div><div class="card admin-stat"><b>${pending}</b><span>waiting review</span></div><div class="card admin-stat"><b>${ls.length}</b><span>local lessons</span></div><div class="card admin-stat"><b>${st.counts?.questions??'—'}</b><span>cloud questions</span></div><div class="card admin-stat"><b>${st.counts?.lessons??'—'}</b><span>cloud lessons</span></div></div><div class="panel"><div class="panel-head"><div><h2>Publish reviewed content</h2><div class="muted">Upsert keeps matching IDs updated instead of creating duplicates.</div></div><span class="tag green">Admin: ${esc(st.profile.name||st.user.email)}</span></div><div class="notice"><b>Recommended:</b> edit/import and test content in Content Admin first. Only use Publish after you are ready for students to receive the changes.</div><div class="form-actions"><button class="small-btn primary" id="publishLocal" ${qs.length+ls.length?'':'disabled'}>Publish reviewed content to cloud</button><button class="small-btn" id="pullCloud">Pull cloud content into local editor</button><button class="small-btn" id="refreshCounts">Refresh counts</button></div></div><div class="panel"><h2>Security model</h2><p class="muted">Students cannot read the master question table. The protected question API serves only session-sized batches; lessons remain directly readable. Only accounts with <b>role=admin</b> can insert, update or delete cloud content.</p><button class="small-btn" id="cloudSignOut">Sign out admin</button></div>`);bind();
}
async function init(){
  if(!EHBackend?.enabled){st.loading=false;render();return}
  try{const sess=await EHBackend.session();st.user=sess?.user||null;if(st.user){st.profile=await EHBackend.getProfile();if(st.profile?.role==='admin')st.counts=await EHBackend.adminCounts()}}catch(e){st.error=e.message}st.loading=false;render();
}
function bind(){
  $('#adminLogin')?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget);st.loading=true;st.error='';render();try{await EHBackend.signIn(String(d.get('email')||'').trim(),String(d.get('password')||''));const sess=await EHBackend.session();st.user=sess?.user||null;st.profile=await EHBackend.getProfile();if(st.profile?.role==='admin')st.counts=await EHBackend.adminCounts()}catch(err){st.error=err.message}st.loading=false;render()});
  $('#publishLocal')?.addEventListener('click',async()=>{if(!confirm('Publish all local custom lessons/questions to the cloud?'))return;st.error='';st.message='Publishing…';render();try{st.counts=await EHBackend.publishContent(safeArray('eh_custom_questions'),safeArray('eh_custom_lessons'));st.message='Cloud content published successfully.'}catch(err){st.message='';st.error=err.message}render()});
  $('#pullCloud')?.addEventListener('click',async()=>{if(!confirm('Replace the local custom editor content with the current cloud content? Download a local backup first if needed.'))return;try{const data=await EHBackend.pullEditableContent();localStorage.setItem('eh_custom_questions',JSON.stringify(data.questions));localStorage.setItem('eh_custom_lessons',JSON.stringify(data.lessons));st.message=`Pulled ${data.questions.length} questions and ${data.lessons.length} lessons into the local editor.`;st.error=''}catch(err){st.error=err.message}render()});
  $('#refreshCounts')?.addEventListener('click',async()=>{try{st.counts=await EHBackend.adminCounts();st.message='Counts refreshed.';st.error=''}catch(err){st.error=err.message}render()});
  $('#cloudSignOut')?.addEventListener('click',async()=>{await EHBackend.signOut();st.user=null;st.profile=null;st.counts=null;st.message='Signed out.';render()});
}
init();
